routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsersProfileController;

Route::middleware('auth')->name('usersProfile.')->prefix('usersProfile')->group(function () {
    Route::get('/', [UsersProfileController::class, 'index'])->name('index');
    Route::put('/update', [UsersProfileController::class, 'update'])->name('update');
    Route::get('/create', [UsersProfileController::class, 'create'])->name('create');
});

Route::get('/images', App\Http\Controllers\ImageController::class)->name('images');

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;

    protected $fillable = [
      'title',
      'description',
      'path',
    ];

    public function user()
    {
        return $this->belonsToMany(User::class);
    }
    public function tags()
    {
        return $this->morphToMany(User::class, 'taggables');
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'bio',
        'username',
        'pic',
        'country',
        'state',
        'city',
        'status',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function setStatusAttribute($value)
    {
        switch ($value) {
            case 'suspend':
                $this->attributes['status'] = 1;
            break;
            case 'private':
                $this->attributes['status'] = 2;
            break;
            case 'public':
                $this->attributes['status'] = 3;
            break;
            default:
            break;
        }
    }

    public function getStatusAttribute()
    {
        switch ($this->attributes['status']) {
            case 1:
                return 'suspend';
            break;
            case 2:
                return 'private';
            break;
            case 3:
                return 'public';
            break;
            default:
            break;
        }
    }

    public function following()
    {
        return $this->belongsToMany(User::class, 'user_user', 'user_id', 'target_user')->wherePivot('status', 'follow');
    }
    public function followers()
    {
        return $this->belongsToMany(User::class, 'user_user', 'target_user', 'user_id')->wherePivot('status', 'follow');
    }
    public function posts()
    {
        return $this->hasMany(Post::class);
    }
    public function savePosts()
    {
        return $this->belongsToMany(Post::class, 'save_posts');
    }
    public function tagsPost()
    {
        return $this->morphedByMany(Post::class, 'taggables');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests;
    use DispatchesJobs;
    use ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ImageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ImageController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $validate = $request->validate([
            'where'  =>  'string|required',
            'id'     =>  'integer|required',
        ]);

        $path = $this->imagePath($validate['where'], $validate['id']);

        $path = Storage::path($path);

        return response()->file($path);
    }
    public function imagePath($where, $id)
    {
        switch ($where) {
            case 'post':
                return \App\Models\Post::select('path')->where('id', $id)->first()->path;
            break;
            case 'avatar':
                return \App\Models\User::select('pic')->where('id', $id)->first()->pic;
            break;
            default:
            break;
        }
    }
}

app/Http/Controllers/UsersProfileController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\Interfaces\UsersRepositoriesInterface;
use App\Http\Requests\UserProfileRequests;

class UsersProfileController extends Controller
{
    private $userRepository;

    public function __construct(UsersRepositoriesInterface $userRepository)
    {
        $this->userRepository = $userRepository;
    }
    public function index(UserProfileRequests $request)
    {
        $this->userRepository->setUser(Auth()->user());

        $request['show'] = isset($request['show']) ? $request['show'] : 'posts';
        $posts = $this->posts($request['show']);
        $postsCount = count($posts);

        $data = [
            "user"  =>  $this->userRepository->getUser(),
            "followingCount" => $this->userRepository->followingCount(),
            "followersCount" => $this->userRepository->followersCount(),
            "postsCount" => $postsCount,
            "posts" =>  $posts,
            "show" => $request['show'],
        ];
        return view('UsersProfile.index')->with('data', $data);
    }
    public function update(UserProfileRequests $request)
    {
        $this->userRepository->setUser(Auth()->user());
        $this->userRepository->updateUser($request);

        return redirect()->back();
    }
    public function create()
    {
        $this->userRepository->setUser(Auth()->user());

        $data = [
            "user" => $this->userRepository->getUser(),
        ];
        return view('UsersProfile.create')->with('data', $data);
    }
    public function posts($request)
    {
        switch ($request) {
           case 'posts':
               return $this->userRepository->posts();
           break;
           case 'tags':
               return $this->userRepository->tagsPost();
           break;
           case 'savePosts':
               return $this->userRepository->savePosts();
           break;
           default:
               return $this->userRepository->posts();
           break;
        }
    }
}

resources/views/UsersProfile/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        @if($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="text-center p-4 order-md-1">
            <div class="text-center d-inline-block w-25 h-25 mw-25 mh-25">
                <img class="img-thumbnail rounded-circle well" src="{{ route('images', ['id'=>$data['user']['id'], 'where'=>'avatar']) }}" alt='this is defualt'>
            </div>
            <form class="needs-validation" action='{{ route('usersProfile.update') }}' enctype="multipart/form-data" method='post'>
                @method('PUT')
                @csrf
                <div class="row">
                    <div class="col-md-6 mb-3">
                        <label for="fullname">{{ __('userProfile.fullName')  }}</label>
                        <input type="text" name="fullname" class="form-control" id="fullname" value="{{ $data['user']['name'] }}">
                        <div class="invalid-feedback">
                            {{ __('userProfile.valids.fullName')  }}
                        </div>
                    </div>
                    <div class="col-md-6 mb-3">
                        <label for="password">{{ __('userProfile.password') }}</label>
                        <input type="password" name="password" class="form-control" id="password" placeholder="*****************">
                        <div class="invalid-feedback">
                            {{ __('userProfile.valids.password')  }}
                        </div>
                    </div>
                </div>

                <div class="mb-3">
                    <label for="username">{{ __('userProfile.username')  }}</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                        <span class="input-group-text">@</span>
                        </div>
                        <input type="text" name="username" class="form-control" id="username" placeholder="{{ $data['user']['username'] }}">
                        <div class="invalid-feedback w-100">
                        {{ __('userProfile.valids.username')  }}
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5 mb-3">
                        <label for="country">{{ __('userProfile.country')  }}</label>
                        <select name="country" class="custom-select d-block w-100" id="country">
                            <option value="">{{ __('userProfile.choose')  }}</option>
                            <option>{{ __('userProfile.countries.iran')  }}</option>
                            <option selected>{{ $data['user']['country'] }}</option>
                        </select>
                        <div class="invalid-feedback">
                        {{ __('userProfile.valids.country')  }}
                        </div>
                    </div>
                    <div class="col-md-4 mb-3">
                        <label for="state">{{ __('userProfile.state')  }}</label>
                        <select name="state" class="custom-select d-block w-100" id="state">
                            <option value="">{{ __('userProfile.choose')  }}</option>
                            <option>{{ __('userProfile.states.tehran')  }}</option>
                            <option>{{ __('userProfile.states.khorasanRazavi')  }}</option>
                            <option selected>{{ $data['user']['state'] }}</option>
                        </select>
                        <div class="invalid-feedback">
                           {{ __('userProfile.valids.state') }}
                        </div>
                    </div>
                    <div class="col-md-3 mb-3">
                        <label for="city">{{ __('userProfile.city')  }}</label>
                        <select name="city" class="custom-select d-block w-100" id="city">
                            <option value="">{{ __('userProfile.choose')  }}</option>
                            <option>{{ __('userProfile.cities.tehran')  }}</option>
                            <option>{{ __('userProfile.cities.sabzevar')  }}</option>
                            <option selected>{{ $data['user']['city'] }}</option>
                        </select>
                        <div class="invalid-feedback">
                            {{ __('userProfile.valids.city') }}
                        </div>
                    </div>
                    <div class="input-group mx-3 mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">{{ __('upload') }}</span>
                        </div>
                        <div class="custom-file">
                            <input type="file" name="avatar" class="custom-file-input" id="avatars">
                            <label class="custom-file-label" for="avatars">{{ __('userProfile.chooseAvatar')  }}</label>
                        </div>
                    </div>
                    <div class="input-group w-25 mx-3 mb-3">
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <input type="checkbox" name="status" value='private' {{ $data['user']['status'] == 'public' ?:'checked' }}>
                            </div>
                        </div>
                        <p class='form-control'>{{ __('userProfile.private') }}</p>
                    </div>
                </div>
                <hr class="mb-4">
                <button class="btn btn-primary btn-lg btn-block" type="submit">{{ __('userProfile.save')  }}</button>
            </form>
        </div>
    </div>
@endsection

resources/views/UsersProfile/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="d-flex justify-content-start p-2 border-bottom border-secondary">
        <div class="w-25 h-25">
            <img class="img-thumbnail rounded-circle w-100 h-100" src="{{ route('images', ['id'=>$data['user']['id'], 'where'=>'avatar']) }}" alt='this is defualt'>
        </div>
        <div class='ml-3 w-75'>
            <div class='d-flex justify-content-around'>
                <h2>{{$data['user']['name']}}</h2>
                <a href='.' class='text-secondary btn'><h4>{{ __('userProfile.following') }}: {{$data['followingCount']}}</h4></a>
                <a href='.' class='text-secondary btn'><h4>{{ __('userProfile.followers') }}: {{$data['followersCount']}}</h4></a>
                <h4 class='text-secondary'>{{ __('userProfile.show.'.$data['show']) }}: {{$data['postsCount']}}</h4>
            </div>
            <h5 class='font-weight-bold mt-3'>{{ __('userProfile.bio') }}</h5>
            @if(!is_null($data['user']['bio']))
            <p>{{$data['user']['bio']}}</p>
            @endif
        </div>

    </div>

        <div class='text-center m-1'>
            <form method="get" action="{{route('usersProfile.index')}}">
                <input class='btn btn-secondary btn-lg w-25' type="submit" name="show" value="posts"/>
                <input class='btn btn-secondary btn-lg w-25' type="submit" name="show" value="tags"/>
            </form>
        </div>
    @if(!is_null($data['posts']))
        <div class="rounded border border-secondary border-bottom-0 p-2 d-flex justify-content-around flex-wrap">
            @foreach($data['posts'] as $post)
                <div class="card text-white bg-dark" style="width: 18rem;">
                <img class="card-img-top" src="{{ route('images', ['where'=>'post','id'=>$post->id]) }}" alt="Card image cap">
                <div class="card-body">
                    <p class="card-text mh-25">{{$post->description}}</p>
                </div>
            </div>
            @endforeach
        </div>
    @endif
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('usersProfile.create') }}">
                                        {{ __('app.profile') }}
                                    </a>
                                    <a class="dropdown-item" href="{{ route('usersProfile.index').'?show=savePosts' }}">
                                        {{ __('app.savePosts') }}
                                    </a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>